### ISSUE TITLE
HTML Special characters

### ISSUE THREAD

**Issue by martoio** [amarmadhavan/prj-rev-bwfs-dasmoto#1]
Check out this article that explains why you need to care about using special characters in HTML: http://text-symbols.com/html/encode/

https://github.com/amarmadhavan/prj-rev-bwfs-dasmoto/blob/852b0fd6454f3b44c583311a48d497fd4b5f28db/ArtProject/index.html#L4

The ampersand should be written as:
``&amp;``

**Comment by amrmad** [comment]
Thanks! TIL '&' & '&amp;' ...
