### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by martoio** [amarmadhavan/prj-rev-bwfs-dasmoto#3]
Make sure you add the ``alt`` attribute to your images to maintain accessibility for all audiences of the page (particularly visually-impaired users). Remember to add it even in these simple projects and it will become a habit. (Hint: as long as you have the ``alt`` attribute with something semi-meaningful, we'll be happy with it).
For more info: https://www.codecademy.com/articles/accessibility

https://github.com/amarmadhavan/prj-rev-bwfs-dasmoto/blob/852b0fd6454f3b44c583311a48d497fd4b5f28db/ArtProject/index.html#L11

**Comment by amrmad** [comment]
Understood and Done!
