### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by martoio** [amarmadhavan/prj-rev-bwfs-dasmoto#4]
While true, you could also do ``.item h2`` since you have that class in the HTML but you never use it:

https://github.com/amarmadhavan/prj-rev-bwfs-dasmoto/blob/852b0fd6454f3b44c583311a48d497fd4b5f28db/ArtProject/resources/css/index.css#L11

**Comment by amrmad** [comment]
Which would allow it to be as specific as possible while still capturing the three required titles. Makes sense. Thanks!
